name: Build and Publish WASM<>JS Bindings

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: .
jobs:
    wasm-publish:
        name: publish-wasm-bindings
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions-rs/toolchain@v1
            with:
              toolchain: nightly-2023-04-17
              override: true
              components: rustfmt, clippy
          - uses: jetli/wasm-pack-action@v0.4.0
          - name: Add wasm32-unknown-unknown target
            run: rustup target add wasm32-unknown-unknown
      
          - name: Install wasm-server-runner
            run: cargo install wasm-server-runner
        
          - name: Add rust-src
            run: rustup component add rust-src --toolchain nightly-2023-04-17-x86_64-unknown-linux-gnu
      
          - name: Build wasm file
            run: wasm-pack build --target web . -- -Z build-std="panic_abort,std"
            
          - name: Update package name in package.json
            run: |
                sed -i 's/"name": "ezkl"/"name": "ezkl-wasm"/' pkg/package.json
            
          - name: Update package.json version to match github tag
            shell: bash
            env:
                RELEASE_NUMBER: ${{ env.EZKL_VERSION }}
            run: |
                sed -i "s/\"version\": \".*\"/\"version\": \"$RELEASE_NUMBER\"/" pkg/package.json
      
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18.12.1'
              registry-url: 'https://registry.npmjs.org'
          - name: Publish to npm
            run: |
              cd pkg
              npm install
              npm ci
              npm publish
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}